### PR TITLE
Disabled Public Open/Close Because people are stupid

### PR DESCRIPTION
**Pull request by JamieD1**

### CODE REVIEW

**Review by Bibby0110 — APPROVED** [review]

**Comment by ReddicusDragon** [comment]
bad pr

**Comment by JamieD1** [comment]
> bad pr

Deal with it.

**Comment by KillerOrcaCora** [comment]
Had it coming, can’t have nice things~

**Comment by ReddicusDragon** [comment]
this should require a council vote

**Comment by ynot01** [comment]
why? what was wrong with public specifically, people were having at least brief discussion over PRs which otherwise wouldn't happen

**Comment by JamieD1** [comment]
> this should require a council vote

BAHAHAHAHAHAHAHAHAHAHAHAHAHAHA

You are funny

**Comment by ReddicusDragon** [comment]
> > this should require a council vote
> 
> BAHAHAHAHAHAHAHAHAHAHAHAHAHAHA
> 
> You are funny

this modifies how the discord is set up and should have some kind of vote to see whether it is in the public interest

**Comment by Bibby0110** [comment]
> > > this should require a council vote
> > 
> > 
> > BAHAHAHAHAHAHAHAHAHAHAHAHAHAHA
> > You are funny
> 
> this modifies how the discord is set up and should have some kind of vote to see whether it is in the public interest

nope

**Comment by JamieD1** [comment]
> > > this should require a council vote
> > 
> > 
> > BAHAHAHAHAHAHAHAHAHAHAHAHAHAHA
> > You are funny
> 
> this modifies how the discord is set up and should have some kind of vote to see whether it is in the public interest

Again, I added it, so I can remove it.

**Comment by ReddicusDragon** [comment]
> > > > this should require a council vote
> > > 
> > > 
> > > BAHAHAHAHAHAHAHAHAHAHAHAHAHAHA
> > > You are funny
> > 
> > 
> > this modifies how the discord is set up and should have some kind of vote to see whether it is in the public interest
> 
> Again, I added it, so I can remove it.

I accept this logic and will now shut my mouth

**Comment by ynot01** [comment]
> why? what was wrong with public specifically, people were having at least brief discussion over PRs which otherwise wouldn't happen

**Comment by JamieD1** [comment]
> > why? what was wrong with public specifically, people were having at least brief discussion over PRs which otherwise wouldn't happen

Merged PRs will still be notified.

**Comment by ynot01** [comment]
that doesn't answer my question, why is it bad for #public to discuss opened PRs?

**Comment by JamieD1** [comment]
> that doesn't answer my question, why is it bad for #public to discuss opened PRs?

Because at the moment its just everyone moaning about simplehorror every single time they open a PR, im done hearing about it.

**Pull request merged**
