### PR TITLE
Removes Map Change yogbot label

### PR DESCRIPTION
**Pull request by ReddicusDragon**
Requested by @wejengin2 so YogBot doesn't apply Map Change and Github Actions applies mapping

### CODE REVIEW

**Comment by alexkar598** [comment]
Are the other labels useful?

**Comment by patpol4** [comment]
What do you mean by other labels.

**Comment by alexkar598** [comment]
image

**Comment by patpol4** [comment]
Oh i wouldnt know, i just use the mapping label a lot, idk if others use the other ones

**Review by adamsong — APPROVED** [review]

**Pull request merged**
